# fly.toml app configuration file generated for uwebsocketjs-demo on 2025-03-17T14:58:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uwebsocketjs-demo'
primary_region = 'sin'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
